# Generated by Django 4.0.4 on 2022-04-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.TextField()),
                ('last_name', models.TextField()),
                ('classroom', models.TextField()),
                ('birthday', models.DateField()),
            ],
        ),
    ]
