# Generated by Django 4.0.4 on 2022-04-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
