# Generated by Django 4.0.4 on 2022-04-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_fist_name_student_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pass_mark',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
    ]
